#
# Copyright (c) 2024 ZettaScale Technology
#
# This program and the accompanying materials are made available under
# the terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#

name: DockerPush

on:
  workflow_dispatch:

jobs:
  docker-build-amd64:
    name: Docker AMD64 build and push
    runs-on: [self-hosted, ubuntu-22.04, X64]
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push AMD64 image
        run: |
          set -xe
          docker build . -f docker/Dockerfile -t zettascaletech/workshop_roscon2024-amd64 --no-cache --platform linux/amd64
          docker tag zettascaletech/workshop_roscon2024-amd64 zettascaletech/workshop_roscon2024-amd64:v2.0
          docker push zettascaletech/workshop_roscon2024-amd64:v2.0

  docker-build-arm64:
    name: Docker ARM64 build and push
    runs-on: [self-hosted, ubuntu-22.04, ARM64]
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ARM64 image
        run: |
          set -xe
          docker build . -f docker/Dockerfile -t zettascaletech/workshop_roscon2024-arm64 --no-cache --platform linux/arm64/v8
          docker tag zettascaletech/workshop_roscon2024-arm64 zettascaletech/workshop_roscon2024-arm64:v2.0
          docker push zettascaletech/workshop_roscon2024-arm64:v2.0

  docker-build-manifest:
    name: Docker manifest build and push
    needs: [docker-build-amd64, docker-build-arm64]
    runs-on: [self-hosted, ubuntu-22.04, X64]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Pull the latest images for both architectures
        run: |
          set -xe
          docker pull zettascaletech/workshop_roscon2024-amd64:v2.0
          docker pull zettascaletech/workshop_roscon2024-arm64:v2.0

      - name: Create and push Docker manifest
        run: |
          set -xe
          docker manifest create --amend zettascaletech/workshop_roscon2024:v2.0 \
            zettascaletech/workshop_roscon2024-amd64:v2.0 \
            zettascaletech/workshop_roscon2024-arm64:v2.0
          docker manifest push zettascaletech/workshop_roscon2024:v2.0
