#
# Copyright (c) 2024 ZettaScale Technology
#
# This program and the accompanying materials are made available under
# the terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#

name: DockerPush

on:
  workflow_dispatch:

jobs:
  docker-build:
    name: Docker build and push
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        env:
          DOCKER_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
        run: |
          echo $DOCKER_TOKEN | docker login --username ${{secrets.DOCKER_HUB_USER}} --password-stdin
          docker buildx create --name builder-context --use --bootstrap
          docker buildx build . -f docker/Dockerfile -t zettascaletech/roscon2024_workshop --no-cache --platform linux/amd64,linux/arm64 --push
